In [6]:
import pandas as pd
import numpy as np

data_set = pd.DataFrame()
data_set = pd.read_csv('multivariable.csv')

In [9]:
data_set.set_index('Dates')

,A UN,A UN.1,A UN.2,A UN.3,A UN.4,A UN.5,A UN.6,A UN.7,A UN.8,AAL UW,...,ZION UW.7,ZION UW.8,ZTS UN,ZTS UN.1,ZTS UN.2,ZTS UN.3,ZTS UN.4,ZTS UN.5,ZTS UN.6,ZTS UN.7
Dates,,,,,,,,,,,,,,,,,,,,,
1/2/2008,25.9577,13431.0000,932000,1446,NaN,0.3368,25.597,25.142,27.483,#NAME?,...,43.243,37.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/3/2008,25.7002,13297.8000,859300,1446,NaN,0.3368,26.124,24.603,27.538,#NAME?,...,43.532,37.676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/4/2008,24.8636,12864.9000,1722300,1446,NaN,0.3368,27.451,26.382,28.027,#NAME?,...,45.173,38.178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/5/2008,24.8636,12864.9000,1722300,1446,NaN,0.3368,27.451,26.382,28.027,#NAME?,...,45.173,38.178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/6/2008,24.8636,12864.9000,1722300,1446,NaN,0.3368,27.451,26.382,28.027,#NAME?,...,45.173,38.178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/7/2008,25.2712,13075.8000,1438200,1446,NaN,0.3368,26.093,26.848,27.779,#NAME?,...,44.221,38.422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/8/2008,25.1854,13031.4000,1837400,1446,NaN,0.3368,26.122,26.724,27.766,#NAME?,...,42.342,38.433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/9/2008,25.2998,13090.6000,1662500,1446,NaN,0.3368,24.487,26.635,27.641,#NAME?,...,41.649,38.337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/10/2008,26.4368,13678.9000,2327900,1446,NaN,0.3368,36.338,28.435,28.657,#NAME?,...,40.901,39.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/11/2008,25.7431,13320.0000,1263900,1446,NaN,0.3368,38.249,29.261,28.985,#NAME?,...,41.061,39.287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/12/2008,25.7431,13320.0000,1263900,1446,NaN,0.3368,38.249,29.261,28.985,#NAME?,...,41.061,39.287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/13/2008,25.7431,13320.0000,1263900,1446,NaN,0.3368,38.249,29.261,28.985,#NAME?,...,41.061,39.287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/14/2008,26.2008,13556.8000,965600,1446,NaN,0.3368,38.604,29.638,29.076,#NAME?,...,38.547,39.269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/15/2008,25.7360,13316.3000,1489900,1446,NaN,0.3368,39.304,30.062,29.203,#NAME?,...,38.873,39.408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/16/2008,25.5071,13197.9000,1780500,1446,NaN,0.3368,39.231,30.096,29.231,#NAME?,...,41.098,39.985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/17/2008,25.2783,13079.5000,1436900,1446,NaN,0.3368,34.665,29.964,29.252,#NAME?,...,42.559,40.799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/18/2008,24.0698,12454.2000,2591800,1446,NaN,0.3368,42.660,32.995,30.412,#NAME?,...,41.013,40.758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/19/2008,24.0698,12454.2000,2591800,1446,NaN,0.3368,42.660,32.995,30.412,#NAME?,...,41.013,40.758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/20/2008,24.0698,12454.2000,2591800,1446,NaN,0.3368,42.660,32.995,30.412,#NAME?,...,41.013,40.758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/21/2008,24.0698,12454.2000,2591800,1446,NaN,0.3368,42.660,32.995,30.412,#NAME?,...,41.013,40.758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/22/2008,23.4835,12150.8000,2381800,1446,NaN,0.3368,43.849,33.505,30.681,#NAME?,...,42.326,41.098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/23/2008,23.8910,12361.7000,2169100,1446,NaN,0.3368,45.503,34.159,30.833,#NAME?,...,50.592,43.782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/24/2008,24.0269,12432.0000,1377600,1446,NaN,0.3368,35.235,32.612,30.849,#NAME?,...,50.125,44.558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/25/2008,23.7337,12280.3000,1146500,1446,NaN,0.3368,33.944,32.143,30.385,#NAME?,...,50.070,44.383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/26/2008,23.7337,12280.3000,1146500,1446,NaN,0.3368,33.944,32.143,30.385,#NAME?,...,50.070,44.383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/27/2008,23.7337,12280.3000,1146500,1446,NaN,0.3368,33.944,32.143,30.385,#NAME?,...,50.070,44.383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/28/2008,23.9697,12402.4000,890600,1446,NaN,0.3368,32.180,32.405,30.441,#NAME?,...,51.091,44.889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/29/2008,23.9411,12387.6000,804700,1446,NaN,0.3368,32.081,32.100,30.428,#NAME?,...,52.648,45.609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/30/2008,24.4417,12646.6000,1217600,1446,NaN,0.3368,35.572,32.132,30.653,#NAME?,...,52.991,45.727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/31/2008,24.2486,12546.7000,2876200,1393,NaN,0.6965,35.535,32.101,30.641,#NAME?,...,54.184,46.257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6/26/2018,61.9800,19830.6328,901152,1206,0.85,-0.8205,20.701,22.223,28.268,#NAME?,...,19.727,24.349,84.01,40649.5358,826031.0,1366.0,2.927,1.62,16.766,16.404
6/27/2018,61.1400,19561.8730,475138,1206,0.85,-0.8205,20.296,22.434,28.282,#NAME?,...,20.292,24.543,83.36,40335.0232,524876.0,1366.0,2.927,1.62,14.726,16.572
6/28/2018,61.2900,19609.8658,370044,1206,0.85,-0.8205,20.996,20.878,28.282,#NAME?,...,20.005,24.382,84.83,41046.3054,635887.0,1366.0,2.927,1.62,17.094,17.361
6/29/2018,61.8400,19785.8395,625008,1206,0.85,-0.8205,22.035,20.751,28.319,#NAME?,...,20.003,24.181,85.19,41220.4970,963013.0,1366.0,2.927,1.62,17.874,16.628
6/30/2018,61.8400,19785.8395,625008,1206,0.85,-0.8205,22.035,20.751,28.319,#NAME?,...,20.003,24.181,85.19,41220.4970,963013.0,1366.0,2.927,1.62,17.874,16.628
7/1/2018,61.8400,19785.8395,625008,1206,0.85,-0.8205,22.035,20.751,28.319,#NAME?,...,20.003,24.181,85.19,41220.4970,963013.0,1366.0,2.927,1.62,17.874,16.628
7/2/2018,61.4700,19667.4572,409844,1206,0.85,-0.8205,19.516,19.808,28.327,#NAME?,...,20.065,24.004,85.65,41443.0751,446776.0,1366.0,2.927,1.62,16.279,16.342
7/3/2018,61.2500,19597.0677,270190,1206,0.85,-0.8205,18.926,19.630,28.329,#NAME?,...,19.812,23.999,86.07,41646.2986,363622.0,1366.0,2.927,1.62,16.682,15.974
7/4/2018,61.2500,19597.0677,270190,1206,0.85,-0.8205,18.926,19.630,28.329,#NAME?,...,19.812,23.999,86.07,41646.2986,363622.0,1366.0,2.927,1.62,16.682,15.974
7/5/2018,61.8000,19773.0414,540699,1206,0.85,-0.8205,19.674,19.876,28.150,#NAME?,...,19.794,23.951,86.15,41685.0078,577353.0,1366.0,2.927,1.62,16.706,15.892
7/6/2018,62.2900,19929.8179,675359,1206,0.85,-0.8205,20.351,20.009,28.181,#NAME?,...,19.914,23.853,86.86,42028.5523,560721.0,1366.0,2.927,1.62,15.385,16.043
7/7/2018,62.2900,19929.8179,675359,1206,0.85,-0.8205,20.351,20.009,28.181,#NAME?,...,19.914,23.853,86.86,42028.5523,560721.0,1366.0,2.927,1.62,15.385,16.043
7/8/2018,62.2900,19929.8179,675359,1206,0.85,-0.8205,20.351,20.009,28.181,#NAME?,...,19.914,23.853,86.86,42028.5523,560721.0,1366.0,2.927,1.62,15.385,16.043
7/9/2018,63.1200,20195.3782,359937,1206,0.85,-0.8205,15.005,19.943,28.136,#NAME?,...,21.377,24.190,87.49,42333.3875,477258.0,1366.0,2.920,1.62,12.842,15.573
7/10/2018,63.6700,20371.3519,528305,1206,0.85,-0.8205,14.346,19.023,28.179,#NAME?,...,18.401,24.203,86.22,41718.8784,847711.0,1366.0,2.920,1.62,15.041,16.153
7/11/2018,62.8600,20112.1906,460503,1206,0.85,-0.8205,14.032,19.049,28.254,#NAME?,...,18.062,24.048,84.50,40886.6298,791397.0,1366.0,2.920,1.62,18.875,16.748
7/12/2018,63.4500,20300.9624,338067,1206,0.85,-0.8205,14.415,18.839,28.265,#NAME?,...,17.949,23.966,85.47,41355.9793,1095044.0,1366.0,2.920,1.62,17.434,16.846
7/13/2018,63.3800,20278.5657,204577,1206,0.85,-0.8205,14.273,18.411,27.962,#NAME?,...,17.615,24.053,86.14,41680.1692,494414.0,1366.0,2.920,1.62,17.763,15.881
7/14/2018,63.3800,20278.5657,204577,1206,0.85,-0.8205,14.273,18.411,27.962,#NAME?,...,17.615,24.053,86.14,41680.1692,494414.0,1366.0,2.920,1.62,17.763,15.881
7/15/2018,63.3800,20278.5657,204577,1206,0.85,-0.8205,14.273,18.411,27.962,#NAME?,...,17.615,24.053,86.14,41680.1692,494414.0,1366.0,2.920,1.62,17.763,15.881
7/16/2018,62.7200,20067.3973,267536,1206,0.85,-0.8205,15.325,18.457,28.002,#NAME?,...,17.898,24.040,84.58,40925.3391,548287.0,1366.0,2.920,1.62,20.332,16.827
7/17/2018,63.0400,20169.7820,315300,1206,0.85,-0.8205,14.958,18.515,27.824,#NAME?,...,18.423,23.966,85.77,41501.1390,446696.0,1366.0,2.920,1.62,21.779,17.205
7/18/2018,62.9900,20153.7844,265332,1206,0.85,-0.8205,14.656,16.635,27.813,#NAME?,...,17.918,24.197,85.95,41588.2347,321297.0,1366.0,2.920,1.62,21.811,17.039
7/19/2018,64.1500,20524.9289,412215,1206,0.85,-0.8205,16.871,17.621,28.012,#NAME?,...,18.519,24.250,85.42,41331.7861,328687.0,1366.0,2.920,1.62,21.362,17.132
7/20/2018,63.8500,20428.9432,491634,1206,0.85,-0.8205,16.166,17.473,27.969,#NAME?,...,18.415,24.077,85.29,41268.8835,503334.0,1366.0,2.920,1.62,20.659,16.646
7/21/2018,63.8500,20428.9432,491634,1206,0.85,-0.8205,16.166,17.473,27.969,#NAME?,...,18.415,24.077,85.29,41268.8835,503334.0,1366.0,2.920,1.62,20.659,16.646
7/22/2018,63.8500,20428.9432,491634,1206,0.85,-0.8205,16.166,17.473,27.969,#NAME?,...,18.415,24.077,85.29,41268.8835,503334.0,1366.0,2.920,1.62,20.659,16.646
7/23/2018,63.7200,20387.3495,408227,1206,0.85,-0.8205,15.587,17.337,27.958,#NAME?,...,18.942,24.216,83.96,40625.3425,684636.0,1366.0,2.910,1.62,20.869,17.200
7/24/2018,64.7900,20729.6982,456347,1206,0.85,-0.8205,15.710,18.117,28.116,#NAME?,...,20.653,24.592,83.50,40402.7644,586041.0,1366.0,2.910,1.62,18.269,17.230
7/25/2018,65.1400,20860.8776,186782,1206,0.85,-0.8205,15.339,18.198,28.106,#NAME?,...,20.665,24.568,85.18,41210.8188,125811.0,1366.0,2.910,1.62,20.617,18.358