In [22]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
from alpha_vantage.timeseries import TimeSeries

ts = TimeSeries(key = 'BEII34ZY6UI335CP', output_format = 'pandas')

stocks = pd.read_csv("https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/data/constituents.csv")

data_set = pd.DataFrame()
i = 1
for t in stocks["Symbol"]:
    #data_set[t] = wb.DataReader(t, data_source = 'morningstar', start = '2007-12-31')["Close"].loc[:'2017-12-31']
    STOCK_av, metadata = ts.get_daily_adjusted(t, outputsize = "full")
    data_set[t] = STOCK_av["5. adjusted close"]
    print(str(i) + t)
    i += 1
data_set

1MMM
2AOS

ValueError: Thank you for using Alpha Vantage! Please visit https://www.alphavantage.co/premium/ if you would like to have a higher API call volume.

In [ ]:
from tia.bbg import LocalTerminal

resp + localT

In [16]:
returns = (data_set / data_set.shift(1)) - 1
annual_returns = returns.mean() * 250

top_20 = annual_returns.sort_values().tail(20)
top_20.to_csv("s&p 2014 to 2017 top 20")

In [17]:
data_set.to_csv("S&P 2014-2017.csv")

In [18]:
top_20

NEM     0.315253
HPQ     0.316643
TSS     0.316711
ADBE    0.318437
BA      0.322445
LRCX    0.330513
GPN     0.334968
HLT     0.342958
ALB     0.349047
AVGO    0.376817
IPGP    0.395422
ATVI    0.431574
DXC     0.472139
AMZN    0.479263
TTWO    0.497550
ALGN    0.505337
NFLX    0.540150
NKTR    0.601794
AMD     0.662783
NVDA    0.841251
dtype: float64

In [25]:
pd.read_csv("s&p 2017 top 20")

    CBOE  0.5555687900350154
0    BBY            0.559895
1    RHT            0.560191
2    CAT            0.567328
3    CNC            0.584833
4   LRCX            0.589137
5   ATVI            0.599536
6    PHM            0.615372
7   PYPL            0.628696
8    DHI            0.648279
9     MU            0.663515
10    BA            0.673931
11  WYNN            0.708890
12  NVDA            0.723481
13  VRTX            0.763702
14  IPGP            0.814314
15  TTWO            0.848090
16  ALGN            0.888447
17   NRG            0.927037
18  NKTR            1.757495

In [26]:
pd.read_csv('s&p 2014 to 2017 top 20')

     NEM  0.31525282080169253
0    HPQ             0.316643
1    TSS             0.316711
2   ADBE             0.318437
3     BA             0.322445
4   LRCX             0.330513
5    GPN             0.334968
6    HLT             0.342958
7    ALB             0.349047
8   AVGO             0.376817
9   IPGP             0.395422
10  ATVI             0.431574
11   DXC             0.472139
12  AMZN             0.479263
13  TTWO             0.497550
14  ALGN             0.505337
15  NFLX             0.540150
16  NKTR             0.601794
17   AMD             0.662783
18  NVDA             0.841251